# STAT 207 Group Lab Assignment 2 - [10 total points]

## Finding Missing Data and Answering Questions

<hr>

## <u>Purpose</u>:
You should work in groups of 2-3 on this report (not working in groups without permission will result in a point deduction). The purpose of this group lab assignment is to understand and wrangle data, so that it would be ready and prepared for future analysis.
<hr>

## <u>Assignment Instructions</u>:

### Contribution Report
These contribution reports should be included in all group lab assignments. In this contribution report below you should list of the following:
1. The netID for the lab submission to be graded.  (Some groups have each member create their own version of the document, but only one needs to be submitted for grading.  Other groups have only one member compose and submit the lab.)
2. Names and netIDs of each team member.
3. Contributions of each team member to report.
4. **For this assignment, add in whether each of you use the gaming hub Steam.  If you do, include your favorite game through Steam.  If not, indicate whether you play any online games (and if so, which one).**

*For example:*

*<u>Teammates:</u>*

*doe105 should be graded.  Grace Jiang (yj31) & Morgan Steimnan (morgan34) worked together on all parts of this lab assignment.  Both use Steam.  Grace favorite games is Palworld and for Morgan is Oxenfree.*,

### Group Roles

You are expected to work in groups of 2-3 on this report.  Since you are working in groups, you may find it helpful to have specified roles.  These roles will likely be helpful in later labs.  Below, I provide roles that can be used for groups of 2 and for groups of 3.  I encourage you to switch roles within this lab report, as possible.  I also encourage you to switch roles for each subsequent lab, as possible, based on your group membership.  

#### Groups of 2

* **Driver**: This student will type the report.  While typing the report, you may be the one who is selecting the functions to apply to the data.
* **Navigator**: This student will guide the process of answering the question.  Specific ways to help may include: outlining the general steps needed to solve a question (providing the overview), locating examples within the course notes, and reviewing each line of code as it is typed.

#### Groups of 3

* **Driver**: This student will type the report.  They may also be the one to select the functions to apply to the data.
* **Navigator**: This student will guide the process of answering the question.  They may select the general approach to answering the question and/or a few steps to be completed along the way. 
* **Communicator**: This student will review the report (as it is typed) to ensure that it is clear and concise.  This student may also locate relevant examples within the course notes that may help complete the assignment.

<hr>

### Imports

In [166]:
#Run this
import pandas as pd                    # imports pandas and calls the imported version 'pd'
import matplotlib.pyplot as plt        # imports the package and calls it 'plt'
import seaborn as sns                  # imports the seaborn package with the imported name 'sns'
sns.set()

## Steam Data

Steam is the world's most popular PC Gaming hub. They have a massive catalog of games, with everything from AAA blockbusters to small indie titles.  

You are a team of data scientists working for Steam, and you are responsible for completing analysis for a report that will go to the executives of Valve (the parent company for Steam).  

Unfortunately, the data were collected with a less than optimal structure.  The dataset is comprised of transactions within the Steam platform for a random sample of 500 steam users along with their purchase and game play behaviors.  It has the following columns:
* user_id,
* game_name,
* activity:
    - purchase: indicating that the user has *purchased* the corresponding game
    - play: indicating that the user has *played* the corresponding game (for at least some amount of time.) 
* hours_played_if_play:
    - if the row corresponds to a 'play' activity, this number represents the number of hours the user has played the game
    - if the row corresponds to a 'purchase' activity, this number is always a 1 (and means nothing... it's a placeholder).

Note that for each user-game combo, there will either be one row (if the game has only been purchased but not played) or two rows (if the game has been both purchased and played).  For example, if I bought Portal, a row would be added to the data representing the purchase of that game by me.  When I open the game and start playing it, a second row would be added to the data representing that I have played the game along with recording my play time for that specific game.

### 1. [1 point] Reading in the Data

First, read the steam_sample.csv file into a dataframe.  Display the first five rows and the number of observations in the data.

Be sure to note the structure of the data (especially how the first two rows relate to each other) when observing the data.

In [167]:
df = pd.read_csv('steam_sample.csv')

In [168]:
df.head()

     user_id  game_name  activity hours_played_if_play
0  308653033   Unturned  purchase                    1
1  308653033   Unturned      play                  0.6
2  308653033  theHunter  purchase                    1
3  144004384     Dota 2  purchase                    1
4  144004384     Dota 2      play                   22

### 2. [3 points] Preparing the Data

In order to prepare the data effectively, perform the following steps:

1. Identify any values (if any) that have been encoded in the csv to represent a **missing value**.  
2. Make sure that Python reads these missing values correctly.  
3. Report the number of rows that have missing values and the proportion of rows with missing values.
4. Drop any observations with missing values.

In [169]:
df['hours_played_if_play'].unique()

array(['1', '0.6', '22', '1028', '1008', '148', '108', '72', '36', '35',
       '32', '21', '16', '15.8', '8.6', '7.8', '7.3', '3.1', '1.9', '1.7',
       '1.1', '0.4', '153', '63', '26', '1.4', '639', '479', '70', '65',
       '33', '30', '19.8', '16.2', '11.3', '4.2', '3.9', '2.3', '0.8',
       '0.7', '0.5', '0.3', '396', '227', '13.4', '12.6', '11.2', '10.1',
       '2.4', '210', '1.2', '0.2', '13.2', '48', '110', '0.1', '67',
       '429', '5.5', '61', '1.6', '18.3', '9.9', '4.7', '1714', '441',
       '197', '147', '117', '86', '73', '49', '46', '31', '24', '20',
       '19.7', '18.2', '14.2', '11.6', '9.8', '9.7', '8.4', '6.5', '4.8',
       '4.1', '3.7', '2.9', '2.7', '2.1', '222', 'unknown', '14.9',
       '14.1', '83', '11.1', '3.2', '6.9', '395', '251', '9.3', '7.4',
       '54', '34', '1.8', '99', '98', '96', '29', '27', '23', '19.1',
       '18.7', '17.5', '17', '16.6', '14.7', '13.3', '10.7', '10.2', '10',
       '9.6', '9.5', '8', '7.9', '7.6', '7', '6.6', '6', '5.8', '5.6',
       '5.3', '4.4', '4.3', '3.3', '3', '2.6', '2.5', '0.9', '6.2',
       '18.9', '2.8', '4814', '4', '494', '1.3', '184', '13.8', '11.4',
       '8.9', '6.7', '496', '1086', '525', '370', '270', '151', '85',
       '66', '56', '15.3', '15.1', '11.5', '7.2', '3.8', '19.6', '2',
       '274', '7.1', '4.9', '4.6', '3.6', '12.1', '103', '13.1', '60',
       '3309', '524', '431', '428', '262', '250', '180', '154', '137',
       '106', '100', '80', '68', '62', '50', '47', '44', '38', '37',
       '13.5', '12', '11.9', '11', '9', '8.2', '8.1', '7.5', '6.8', '5.1',
       '5', '2.2', '1.5', '57', '964', '41', '12.5', '10.4', '361', '88',
       '82', '17.6', '17.1', '16.3', '15.2', '14.6', '11.7', '8.8', '8.3',
       '5.9', '717', '303', '13.9', '10.6', '2179', '526', '28', '14.5',
       '12.4', '149', '10.8', '15', '19.9', '113', '76', '646', '25',
       '14', '546', '11.8', '381', '16.1', '215', '81', '19.5', '248',
       '59', '42', '13.7', '3626', '997', '665', '622', '522', '344',
       '224', '213', '208', '186', '95', '79', '78', '40', '18.1', '18',
       '17.8', '17.4', '15.9', '15.5', '14.8', '12.3', '3.5', '3.4',
       '116', '6.1', '393', '332', '238', '307', '157', '550', '52',
       '9.2', '1343', '13.6', '8.5', '15.7', '202', '530', '43', '6.3',
       '518', '232', '175', '58', '90', '15.4', '14.4', '193', '173',
       '12.2', '1339', '190', '121', '7.7', '4.5', '249', '77', '399',
       '278', '91', '6.4', '162', '89', '17.2', '9.1', '652', '517',
       '125', '105', '75', '55', '17.9', '10.9', '8.7', '10.3', '5.7',
       '5.4', '10.5', '118', '9.4', '284', '71', '19.3', '209', '5.2',
       '1605', '1540', '710', '617', '312', '644', '189', '191', '176',
       '136', '115', '39', '19', '69', '1912', '777', '686', '15.6',
       '18.4', '539', '1760', '165', '17.3', '112', '386', '720', '466',
       '124', '109', '87', '14.3', '676', '449', '236', '119', '53', '45',
       '3178', '1302', '795', '174', '123', '104', '101', '64', '51',
       '16.9', '16.8', '16.5', '1030', '145', '214', '11754', '144',
       '579', '263', '241', '160', '141', '120', '92', '13', '289',
       '1337', '17.7', '2258', '217', '135', '389', '228', '187', '111',
       '357', '923', '172', '1369', '1049', '488', '130', '126', '93',
       '18.8', '1064', '18.5', '12.9', '458', '418', '194', '272', '16.4',
       '419', '107', '290', '1499', '891', '693', '302', '273', '264',
       '158', '133', '1301', '485', '1754', '231', '12.8', '132', '733',
       '230', '127', '627', '994', '387', '487', '528', '138', '809',
       '511', '2055', '402', '451', '170', '527', '206', '164', '207',
       '196', '143', '1295', '520', '364', '1704'], dtype=object)

In [170]:
df = pd.read_csv('steam_sample.csv', na_values = ['unknown'])

In [171]:
df.isna().sum()

user_id                 0
game_name               0
activity                0
hours_played_if_play    6
dtype: int64

In [172]:
print('Rows With Missing Values:') 
print(df['hours_played_if_play'].isna().sum())
print('Proportion of Rows with Missing Values:') 
print(df['hours_played_if_play'].isna().sum() / len(df))

Rows With Missing Values:
6
Proportion of Rows with Missing Values:
0.0007686395080707148

In [173]:
df = df.dropna()

### 3. [1 point] Interpreting Missing Data

We dropped observations above that had any missing values.  Are you concerned that the decision to drop observations as the way to handle missing data may not have been best?  Briefly explain.

### We don't think that there should be great concern as it was only 6 rows out of 7806 rows.

### 4. [1 point] Separate the Data

In this analysis, we would like to answer questions based on purchases and based on play time.  Create two new dataframes:

- one that is comprised of the purchase rows for the games that were purchased
- one that is comprised of the play rows for the games that were played

In [181]:
df_purchase = df[ df.activity == 'purchase']

In [182]:
df_play = df[ df.activity == 'play']

### 5. [2 points] Game Play Time Question

Review the amount of time played for each row (user-game combination); you can choose your favorite method to review these amounts.  Are there any of these values that you suspect may not be accurate?  Explain.  

Do you have any questions about the game play time variable?

In [176]:
df_play_group = df_play.groupby('user_id').agg('sum').reset_index()[['user_id', 'game_name', 'hours_played_if_play']]
#df_play_group['hours_played_if_play'] = df_play_group['hours_played_if_play'].astype('int64')
df_play_group

,user_id,game_name,hours_played_if_play
0,683019,Counter-Strike SourceF1 2014,42.9
1,4877411,Counter-Strike Condition ZeroCounter-StrikeHAW...,280.8
2,4897767,Counter-Strike,1.6
3,5600822,Counter-Strike Source,6.6
4,9245216,Natural Selection 2Dota 2RIFTSid Meier's Civil...,123.0
...,...,...,...
445,305086197,Dota 2,2.0
446,306950369,Euro Truck Simulator 2,0.6
447,308468736,Magic DuelsWar Thunder,1.3
448,308653033,Unturned,0.6
449,309265377,BrawlhallaMicroVolts Surge,2.8

In [177]:
df_play_group[df_play_group.hours_played_if_play >= 1000]

,user_id,game_name,hours_played_if_play
8,14962163,Counter-Strike Global OffensiveRobocraftCounte...,1547.9
10,16084897,Star Trek OnlineThe Elder Scrolls V SkyrimFall...,2215.3
12,19696244,The Elder Scrolls V SkyrimPAYDAY 2Team Fortres...,2883.1
24,32749624,Counter-StrikeCounter-Strike Global OffensiveG...,4937.3
28,35729292,Dota 2Counter-Strike Global OffensiveCounter-S...,2687.0
34,39911920,Counter-StrikeCounter-Strike Condition Zero,2290.0
39,43684632,Counter-Strike Global OffensiveFootball Manage...,9546.3
43,48798067,Mount & Blade WarbandCounter-Strike Global Off...,9427.2
49,54103616,Counter-Strike Global OffensiveCounter-StrikeL...,2568.1
55,56436338,Football Manager 2009Football Manager 2015Foot...,3506.0
57,58289184,PAYDAY 2Call of Duty Modern Warfare 2 - Multip...,2517.6
59,60296891,Dota 2Left 4 Dead 2TerrariaSkullgirlsTeam Fort...,1316.7
62,61632730,War ThunderH1Z1Call of Duty Modern Warfare 2 -...,1646.9
63,62078957,Clicker HeroesCounter-StrikeCounter-Strike Glo...,3520.5
75,73017395,Sid Meier's Civilization V,11754.0
77,75377823,Sid Meier's Civilization VTotal War ROME II - ...,1916.0
78,75598925,Left 4 Dead 2Borderlands 2Team Fortress 2Don't...,2796.6
86,79474322,Total War ROME II - Emperor EditionThe Elder S...,1973.9
95,85673716,The Elder Scrolls V SkyrimCrusader Kings IIDeu...,1137.7
96,86866292,Dota 2Disciples II Gallean's ReturnBioShock In...,1623.0
97,87071236,Dota 2Stronghold KingdomsSid Meier's Civilizat...,3180.6
99,88035166,Out of the Park Baseball 16Out of the Park Bas...,2094.0
110,93290614,Dota 2,1760.0
120,99077905,Dota 2BorderlandsAlan WakeFallout 4DarksidersI...,6838.4
121,99096740,Dota 2WarframeFar Cry 3Grand Theft Auto VDayZC...,2447.8
125,101339059,Total War ROME II - Emperor EditionBlood Bowl ...,4496.4
132,107476377,Sid Meier's Civilization IV Beyond the SwordEm...,1340.1
141,113546110,The Elder Scrolls V SkyrimTotal War SHOGUN 2Th...,1377.5
147,116831291,Dota 2PAYDAY 2The Legend of Korra,1459.3
149,118852041,Counter-Strike Global OffensiveArma 2 Operatio...,2877.1
157,122620165,Dota 2Counter-Strike Global OffensiveCounter-S...,1569.2
159,123917008,Dota 2,1301.0
164,126191291,Counter-Strike Global OffensiveTeam Fortress 2...,1609.1
177,131217195,Dota 2,2179.0
225,159077305,Counter-Strike Global OffensiveAssassin's Cree...,1292.4
249,171847029,Counter-Strike Global OffensiveDayZHeroes & Ge...,1380.5
257,174287424,ARK Survival EvolvedMight & Magic Heroes VI7 D...,1107.1
332,212915541,Dota 2,1605.0
333,213610494,Counter-Strike Global OffensiveRustRobocraftAr...,1072.2
334,213854339,Eastside Hockey ManagerFranchise Hockey Manage...,1369.2

I think there could be some false inputs in the hours played column. A question I have for that column is if it counts when a game comes out and is purchased in pre-release.

### 6. [2 points] Purchasing to Playing?

Overall, of all of the purchases represented in this data, what proportion have been played?  Of all the purchases in the data, what proportion remain "unopened", that is, unplayed?

What factors do you anticipate might affect whether a given game is played or not after being purchased?

In [185]:
df_purchase_unopen = df_play[ df_play.hours_played_if_play == 1]
df_purchase_open = df_play[ df_play.hours_played_if_play != 1]
print('Proportion of purchases that have been played')
print(df_purchase_open)

,user_id,game_name,activity,hours_played_if_play
1,308653033,Unturned,play,0.6
4,144004384,Dota 2,play,22.0
6,54103616,Counter-Strike Global Offensive,play,1028.0
8,54103616,Counter-Strike,play,1008.0
10,54103616,Left 4 Dead,play,148.0
...,...,...,...,...
7793,99096740,Crysis,play,5.3
7795,99096740,Assassin's Creed II,play,2.7
7797,99096740,Hitman Blood Money,play,1.3
7799,99096740,The Binding of Isaac Rebirth,play,0.7
7801,99096740,SimCity 4 Deluxe,play,0.2